name: CI/CD Pipeline, Build push and deploy with podman

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch (adjust if you use a different branch)
  pull_request:
    branches:
      - main  # Trigger on PRs to 'main' branch

jobs:
  # Step 1: Build and Test Docker Image
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
  # Step 2: Deploy Docker Image (CD)
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # Only runs if build-and-test is successful

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
  # Install Podman
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Podman image
      - name: Build Podman image
        run: podman build -t rajalakshmi1205/project-llm:v1 .

      # Push the Podman image to Docker Hub
      - name: Push Podman image
        run: podman push rajalakshmi1205/project-llm:v1
     
     
     # Run the Podman image        
      - name: Run Podman container
        run: podman run -e AIPROXY_TOKEN=$AIPROXY_TOKEN -p 8000:8000 rajalakshmi1205/project-llm:v1
        
      - name: Deploy to production (or staging)
        run: |
          echo "Deploying to production..."

          # Replace this with your actual deployment commands (e.g., using kubectl for Kubernetes)
          # kubectl apply -f deployment.yaml  # Example deployment command
