name: CI/CD Pipeline, Build push and deploy with podman

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch (adjust if you use a different branch)
  pull_request:
    branches:
      - main  # Trigger on PRs to 'main' branch

jobs:
  # Step 1: Build and Test Docker Image
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
  # Step 2: Deploy Docker Image (CD)
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # Only runs if build-and-test is successful

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
  # Install Podman
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & push the Podman image
      -  name: Build the Podman image
         run: |
           podman build -t project-llm:v1 .
           podman tag project-llm:v1 docker.io/rajalakshmi1205/project-llm:v1
           podman push docker.io/rajalakshmi1205/project-llm:v1
             
      - name: Deploy to production (or staging)
        run: |
          echo "Deploying to production..."

          # Replace this with your actual deployment commands (e.g., using kubectl for Kubernetes)
          # kubectl apply -f deployment.yaml  # Example deployment command
