name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch (adjust if you use a different branch)
  pull_request:
    branches:
      - main  # Trigger on PRs to 'main' branch

jobs:
  # Step 1: Build and Test Docker Image
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t rajalakshmi1205/tdsdocker:latest .

      - name: Run tests (example with pytest)
        run: |
          # Run your tests here (e.g., using pytest)
          pytest tests/

  # Step 2: Deploy Docker Image (CD)
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Only runs if build-and-test is successful

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build -t rajalakshmi1205/tdsdocker:latest .
          docker push rajalakshmi1205/tdsdocker:latest

      - name: Deploy to production (or staging)
        run: |
          # Replace this with your actual deployment commands (e.g., using kubectl for Kubernetes)
          echo "Deploying to production..."
          # kubectl apply -f deployment.yaml  # Example deployment command
